### ISSUE TITLE
results.

### ISSUE THREAD

**Issue by despoinamusica39** [hulyak/song-finder#1]
WOO WHAT AMAZINGGGGGGGG WEB.PLEASE I AM BEGGING YOU COULD YOU MAKE IT LOAD UNLIMITED RESULTS?PLEASSEEEEEEEEEEEE...I LOVE SPANISH MUSIC SO MUCH AND IT WOULB BE GREATTTTTTTTTTTT FIND UNLIMITED SONGS AND ALBUMS!!!!PLEASEEEEEEEEEEEEEE

**Comment by hulyak** [comment]
I increased to max of 200 songs 👍
